In [1]:
import numpy as np

# creating a numpy array 

### 1)by using list

In [2]:
l1=[1.45,1.98,'list']
ar1=np.array(l1)
ar1

array(['1.45', '1.98', 'list'],
      dtype='<U32')

### 2)by using arrange method 

In [3]:
ar2=np.arange(10)
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar2=np.arange(1,10,2)
ar2

array([1, 3, 5, 7, 9])

### 3)random generation

In [5]:
ar3=np.random.rand(5)
ar3

array([ 0.88825872,  0.72882646,  0.86512706,  0.91836288,  0.48981648])

In [43]:
#create 2d array of shape 5*3 to contain random decimal bet 5&10
np.random.uniform(5,10,size=(5,3))

array([[ 5.07534122,  6.59332573,  6.52248657],
       [ 5.18935152,  6.32747271,  5.28349031],
       [ 5.98739377,  7.52743558,  8.82045691],
       [ 7.70531861,  8.641399  ,  8.72199889],
       [ 8.51358715,  7.97266806,  5.19778554]])

# 4)by using repeat

In [6]:
ar4=np.repeat(1,10)
ar4

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 5)converting dataframe to numpy array

In [7]:
import pandas as pd
weather_data={
    'day':['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature':[32,35,28,24,32,31],
    'windspeed':[6,7,2,7,4,2],
    'event':['Rain','Sunny','Snow','Snow','Rain','Sunny']
}
df1=pd.DataFrame(weather_data)
ar5=df1.as_matrix()
ar5

array([['1/1/2017', 'Rain', 32, 6],
       ['1/2/2017', 'Sunny', 35, 7],
       ['1/3/2017', 'Snow', 28, 2],
       ['1/4/2017', 'Snow', 24, 7],
       ['1/5/2017', 'Rain', 32, 4],
       ['1/6/2017', 'Sunny', 31, 2]], dtype=object)

In [8]:
# another way is to by using .values()
ar5=df1.values
ar5

array([['1/1/2017', 'Rain', 32, 6],
       ['1/2/2017', 'Sunny', 35, 7],
       ['1/3/2017', 'Snow', 28, 2],
       ['1/4/2017', 'Snow', 24, 7],
       ['1/5/2017', 'Rain', 32, 4],
       ['1/6/2017', 'Sunny', 31, 2]], dtype=object)

# Operations on numpy array

### checking version of numpy

In [9]:
np.__version__

'1.13.1'

In [10]:
#numpy assumes all the elements of array as of saame data types
type(ar1)

numpy.ndarray

In [11]:
#numpy behaves differently from list
ar3=np.array([1,2,3])
print(l1+l1)
print(ar3+ar3)

[1.45, 1.98, 'list', 1.45, 1.98, 'list']
[2 4 6]


In [12]:
#subsetting is same
print(l1[1])
print(ar3[1])

1.98
2


In [13]:
bmi=np.array([20,21,22,23,24,25])
print(bmi[1])
print(bmi>23)
print(bmi[bmi>23])
print(type(bmi))
print(bmi.max())  #similarly min()

21
[False False False False  True  True]
[24 25]
<class 'numpy.ndarray'>
25


#  2D numpy array

### can be created using
### 1-list of list

In [14]:
np_2d=np.array([[1,2,3,4],[5,6,7,8]])
np_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### 2-converting 1d to 2d using reshape method

In [15]:
d_1=np.array([1,2,3,4,5,6])
d_2= d_1.reshape(2,-1)  #  -1 for automatically deciding the number of columns
print(d_2)
d_2=d_1.reshape(3,2)
print(d_2)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


### operations

In [16]:
#to check shape
np_2d.shape

(2, 4)

In [17]:
#to check size
np_2d.size

8

In [18]:
print(np_2d[0])
print(np_2d[0][1])    #this is similar to np_2d[0,1]
print(np_2d[:,1:2])

[1 2 3 4]
2
[[2]
 [6]]


# statistics with numpy 

In [19]:
np.mean(np_2d[0,:])

2.5

In [20]:
np.median(np_2d[0,:])

2.5

In [21]:
np.std(np_2d[0,:])

1.1180339887498949

In [22]:
np.sum(np_2d[0,:])

10

In [23]:
np.sort(np_2d[0,:])

array([1, 2, 3, 4])

In [24]:
np.corrcoef(np_2d[:,0],np_2d[:,1])  #to check co relation between columns

array([[ 1.,  1.],
       [ 1.,  1.]])

# Stack 2 arrays vertically

In [25]:
a=np.arange(10).reshape(2,-1)
b=np.arange(10).reshape(2,-1)
#method 1
np.concatenate([a,b],axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
#method 2
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
#method 3
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
#for horizontal, axis=1 ,np.c_ and hstack
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

# generating some patterns

In [29]:
a=np.array([1,2,3])
#repeat one one element of an array n times
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [30]:
#repeat full array n times
np.tile(a,3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

# finding common items between 2 arrays

In [31]:
a=np.arange(10)
b=np.arange(0,10,2)
np.intersect1d(a,b)

array([0, 2, 4, 6, 8])

# remove elements from one array that exists in another

In [32]:
print(a)
print(b)
np.setdiff1d(a,b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


array([1, 3, 5, 7, 9])

# get positions where elements of 2 array match

In [33]:
a=np.arange(10)
b=np.arange(0,10,2)
print(a)
print(b)
np.where(a == b)    #here error coz size is not same

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


/home/purva/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """


(array([], dtype=int64),)

In [34]:
a=np.arange(10)
b=np.arange(0,20,2)
print(a)
print(b)
np.where(a == b) 

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


(array([0]),)

# extracting elements between given range

In [35]:
a=np.arange(15)
#m1
index=np.where((a>=5)&(a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
#another method m2
index=np.where(np.logical_and(a>=5,a<=10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [37]:
#m3
a[(a>=5)&(a<=10)]

array([ 5,  6,  7,  8,  9, 10])

# swapping columns n rows

In [38]:
ar=np.arange(9).reshape(3,3)
#for column swap
ar[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [39]:
#for row swap
ar[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

# to reverse rows n columns

In [40]:
#to reverse rows
ar[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [42]:
#to reverse columns
ar[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

# to print only 3 decimal places

In [45]:
a=np.array([7.9864545,5.86856])
np.set_printoptions(precision=3)
a

array([ 7.986,  5.869])

# suppressing scientific notation

In [47]:
np.random.seed(100)
rand=np.random.random([3,3])/1e3
np.set_printoptions(suppress=True)
rand

array([[ 0.001,  0.   ,  0.   ],
       [ 0.001,  0.   ,  0.   ],
       [ 0.001,  0.001,  0.   ]])

# limiting number of items printed in output

In [48]:
ar=np.array([1,2,3,4,5,6,7,8,9,10])
np.set_printoptions(threshold=6)
ar

array([ 1,  2,  3, ...,  8,  9, 10])

# to print full array without truncating

In [49]:
np.set_printoptions(threshold=np.nan)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# normalize values exactly between 0 & 1

In [52]:
#array-min/(max-min)  or max-min=array.ptp()
s = (ar-ar.min())/(ar.max()-ar.min())
s

array([ 0.   ,  0.111,  0.222,  0.333,  0.444,  0.556,  0.667,  0.778,
        0.889,  1.   ])